{
  "hash": "bdec72074811b7189d89a2a75e2ab139",
  "result": {
    "markdown": "---\ntitle: \"R Coding Exercise\"\noutput:\n  html_document:\n    toc: FALSE\n---\n\n\n*This page is the introductory coding exercise in R for this class. I\nwill be working with the dslabs package data to perform data processing,\nvisual plotting, and model fitting.*\n\n## Receiving and summarizing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Load package\nlibrary(dslabs)\nlibrary(tidyverse)\nlibrary(dplyr)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Look at help file for gapminder dataset\nhelp(gapminder)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nstarting httpd help server ... done\n```\n:::\n\n```{.r .cell-code}\n#The gapminder dataset contains health \n#and income outcomes for 184 countries \n#from 1960 to 2016.\n\n#get an overview of the data structure\nstr(gapminder)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t10545 obs. of  9 variables:\n $ country         : Factor w/ 185 levels \"Albania\",\"Algeria\",..: 1 2 3 4 5 6 7 8 9 10 ...\n $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...\n $ infant_mortality: num  115.4 148.2 208 NA 59.9 ...\n $ life_expectancy : num  62.9 47.5 36 63 65.4 ...\n $ fertility       : num  6.19 7.65 7.32 4.43 3.11 4.55 4.82 3.45 2.7 5.57 ...\n $ population      : num  1636054 11124892 5270844 54681 20619075 ...\n $ gdp             : num  NA 1.38e+10 NA NA 1.08e+11 ...\n $ continent       : Factor w/ 5 levels \"Africa\",\"Americas\",..: 4 1 1 2 2 3 2 5 4 3 ...\n $ region          : Factor w/ 22 levels \"Australia and New Zealand\",..: 19 11 10 2 15 21 2 1 22 21 ...\n```\n:::\n\n```{.r .cell-code}\n#get a summary of data\nsummary(gapminder)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                country           year      infant_mortality life_expectancy\n Albania            :   57   Min.   :1960   Min.   :  1.50   Min.   :13.20  \n Algeria            :   57   1st Qu.:1974   1st Qu.: 16.00   1st Qu.:57.50  \n Angola             :   57   Median :1988   Median : 41.50   Median :67.54  \n Antigua and Barbuda:   57   Mean   :1988   Mean   : 55.31   Mean   :64.81  \n Argentina          :   57   3rd Qu.:2002   3rd Qu.: 85.10   3rd Qu.:73.00  \n Armenia            :   57   Max.   :2016   Max.   :276.90   Max.   :83.90  \n (Other)            :10203                  NA's   :1453                    \n   fertility       population             gdp               continent   \n Min.   :0.840   Min.   :3.124e+04   Min.   :4.040e+07   Africa  :2907  \n 1st Qu.:2.200   1st Qu.:1.333e+06   1st Qu.:1.846e+09   Americas:2052  \n Median :3.750   Median :5.009e+06   Median :7.794e+09   Asia    :2679  \n Mean   :4.084   Mean   :2.701e+07   Mean   :1.480e+11   Europe  :2223  \n 3rd Qu.:6.000   3rd Qu.:1.523e+07   3rd Qu.:5.540e+10   Oceania : 684  \n Max.   :9.220   Max.   :1.376e+09   Max.   :1.174e+13                  \n NA's   :187     NA's   :185         NA's   :2972                       \n             region    \n Western Asia   :1026  \n Eastern Africa : 912  \n Western Africa : 912  \n Caribbean      : 741  \n South America  : 684  \n Southern Europe: 684  \n (Other)        :5586  \n```\n:::\n\n```{.r .cell-code}\n#determine the type of object gapminder is\nclass(gapminder)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"data.frame\"\n```\n:::\n:::\n\n\n## Subset data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#pull out data points (rows) \n#related to Africa and assign to object `africadata`\nafricadata <- filter(gapminder, continent == \"Africa\")\n\n#check new object\nstr(africadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t2907 obs. of  9 variables:\n $ country         : Factor w/ 185 levels \"Albania\",\"Algeria\",..: 2 3 18 22 26 27 29 31 32 33 ...\n $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...\n $ infant_mortality: num  148 208 187 116 161 ...\n $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...\n $ fertility       : num  7.65 7.32 6.28 6.62 6.29 6.95 5.65 6.89 5.84 6.25 ...\n $ population      : num  11124892 5270844 2431620 524029 4829291 ...\n $ gdp             : num  1.38e+10 NA 6.22e+08 1.24e+08 5.97e+08 ...\n $ continent       : Factor w/ 5 levels \"Africa\",\"Americas\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ region          : Factor w/ 22 levels \"Australia and New Zealand\",..: 11 10 20 17 20 5 10 20 10 10 ...\n```\n:::\n\n```{.r .cell-code}\nsummary(africadata)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         country          year      infant_mortality life_expectancy\n Algeria     :  57   Min.   :1960   Min.   : 11.40   Min.   :13.20  \n Angola      :  57   1st Qu.:1974   1st Qu.: 62.20   1st Qu.:48.23  \n Benin       :  57   Median :1988   Median : 93.40   Median :53.98  \n Botswana    :  57   Mean   :1988   Mean   : 95.12   Mean   :54.38  \n Burkina Faso:  57   3rd Qu.:2002   3rd Qu.:124.70   3rd Qu.:60.10  \n Burundi     :  57   Max.   :2016   Max.   :237.40   Max.   :77.60  \n (Other)     :2565                  NA's   :226                     \n   fertility       population             gdp               continent   \n Min.   :1.500   Min.   :    41538   Min.   :4.659e+07   Africa  :2907  \n 1st Qu.:5.160   1st Qu.:  1605232   1st Qu.:8.373e+08   Americas:   0  \n Median :6.160   Median :  5570982   Median :2.448e+09   Asia    :   0  \n Mean   :5.851   Mean   : 12235961   Mean   :9.346e+09   Europe  :   0  \n 3rd Qu.:6.860   3rd Qu.: 13888152   3rd Qu.:6.552e+09   Oceania :   0  \n Max.   :8.450   Max.   :182201962   Max.   :1.935e+11                  \n NA's   :51      NA's   :51          NA's   :637                        \n                       region   \n Eastern Africa           :912  \n Western Africa           :912  \n Middle Africa            :456  \n Northern Africa          :342  \n Southern Africa          :285  \n Australia and New Zealand:  0  \n (Other)                  :  0  \n```\n:::\n:::\n\n\nNote that only rows where Africa is listed as the continent are in this\ndataset (2907 observations)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Now, pull out the columns \n#for infant mortality & life\n#expectancy and population & \n#life expectancy for African \n#countries and assign to objects\nMortExpec <- africadata %>% select(infant_mortality, life_expectancy)\n\nPopExpec <- africadata %>% select(life_expectancy, population)\n\n#view MortExpec object\nstr(MortExpec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t2907 obs. of  2 variables:\n $ infant_mortality: num  148 208 187 116 161 ...\n $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...\n```\n:::\n\n```{.r .cell-code}\nsummary(MortExpec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n infant_mortality life_expectancy\n Min.   : 11.40   Min.   :13.20  \n 1st Qu.: 62.20   1st Qu.:48.23  \n Median : 93.40   Median :53.98  \n Mean   : 95.12   Mean   :54.38  \n 3rd Qu.:124.70   3rd Qu.:60.10  \n Max.   :237.40   Max.   :77.60  \n NA's   :226                     \n```\n:::\n\n```{.r .cell-code}\n#view PopExpec object\nstr(PopExpec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t2907 obs. of  2 variables:\n $ life_expectancy: num  47.5 36 38.3 50.3 35.2 ...\n $ population     : num  11124892 5270844 2431620 524029 4829291 ...\n```\n:::\n\n```{.r .cell-code}\nsummary(PopExpec)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n life_expectancy   population       \n Min.   :13.20   Min.   :    41538  \n 1st Qu.:48.23   1st Qu.:  1605232  \n Median :53.98   Median :  5570982  \n Mean   :54.38   Mean   : 12235961  \n 3rd Qu.:60.10   3rd Qu.: 13888152  \n Max.   :77.60   Max.   :182201962  \n                 NA's   :51         \n```\n:::\n:::\n\n\nFor both new objects, all observations were used (2907 rows) but each\nobject has two columns (two variables each). All other variables\n(including country) have been removed.\n\n## Plotting the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#plot life expectancy as \n#a function of infant mortality\nggplot(MortExpec) +\n  geom_point(aes(infant_mortality, life_expectancy))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 226 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![Life expectancy vs infant mortality](coding_exercise_files/figure-html/fig1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#| label: fig2\n#| fig-cap: Life expectancy vs population size\n#plot life expectancy as \n#a function of population size\nggplot(PopExpec) +\n  geom_point(aes(population, life_expectancy))+\n  scale_x_continuous(trans = \"log\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 51 rows containing missing values (`geom_point()`).\n```\n:::\n\n::: {.cell-output-display}\n![Life expectancy vs infant mortality](coding_exercise_files/figure-html/fig1-2.png){width=672}\n:::\n:::\n\n\nLife expectancy has a negative correlation with infant mortality. As\ninfant mortality increases, life expectancy decreases. The warning\nmessage indicated 226 data points could not be plotted.\n\nLife expectancy has a positive correlation with population size. As\npopulation increases, life expectancy increases. Note that some data\npoints seem to trend together; this is because the grouped data is from\nthe same country over multiple years. The warning message indicated that\n51 points could not be plotted.\n\n## Data cleaning\n\nAs noted in the plotting stage, there are some missing data points for\nsome countries for some years. Let's try to find the years with missing\ndata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#find years with missing \n#data for infant mortality \n#using `africadata`\n\nafricadata %>%    filter(is.na(infant_mortality))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                     country year infant_mortality life_expectancy fertility\n1                 Cape Verde 1960               NA           50.12      6.89\n2                       Chad 1960               NA           40.95      6.25\n3                   Djibouti 1960               NA           45.77      6.46\n4          Equatorial Guinea 1960               NA           37.69      5.51\n5                    Eritrea 1960               NA           39.03      6.90\n6                      Gabon 1960               NA           38.83      4.38\n7                     Guinea 1960               NA           35.71      6.10\n8              Guinea-Bissau 1960               NA           43.14      5.83\n9                      Niger 1960               NA           36.82      7.05\n10              South Africa 1960               NA           49.01      6.17\n11                    Angola 1961               NA           36.53      7.35\n12                Cape Verde 1961               NA           50.27      6.92\n13                      Chad 1961               NA           41.35      6.27\n14                   Comoros 1961               NA           44.47      6.85\n15          Congo, Dem. Rep. 1961               NA           44.25      6.02\n16                  Djibouti 1961               NA           46.28      6.49\n17         Equatorial Guinea 1961               NA           38.04      5.52\n18                   Eritrea 1961               NA           39.35      6.87\n19                  Ethiopia 1961               NA           38.35      6.88\n20                     Gabon 1961               NA           39.15      4.46\n21             Guinea-Bissau 1961               NA           43.39      5.77\n22                Madagascar 1961               NA           42.54      7.30\n23                Mozambique 1961               NA           38.79      6.60\n24                   Namibia 1961               NA           47.70      6.17\n25                     Niger 1961               NA           36.97      7.08\n26                   Nigeria 1961               NA           41.00      6.35\n27              South Africa 1961               NA           49.40      6.14\n28                    Angola 1962               NA           37.08      7.39\n29                Cape Verde 1962               NA           50.43      6.95\n30                      Chad 1962               NA           41.76      6.29\n31                   Comoros 1962               NA           44.89      6.90\n32          Congo, Dem. Rep. 1962               NA           44.61      6.03\n33                  Djibouti 1962               NA           46.79      6.53\n34         Equatorial Guinea 1962               NA           38.38      5.53\n35                   Eritrea 1962               NA           39.69      6.84\n36                  Ethiopia 1962               NA           38.94      6.88\n37                     Gabon 1962               NA           39.56      4.54\n38             Guinea-Bissau 1962               NA           43.64      5.67\n39                Madagascar 1962               NA           43.12      7.30\n40                Mozambique 1962               NA           39.40      6.60\n41                   Namibia 1962               NA           48.31      6.18\n42                     Niger 1962               NA           37.10      7.12\n43              South Africa 1962               NA           49.78      6.10\n44                    Angola 1963               NA           37.63      7.41\n45                Cape Verde 1963               NA           50.59      6.98\n46                      Chad 1963               NA           42.17      6.30\n47                   Comoros 1963               NA           45.32      6.94\n48          Congo, Dem. Rep. 1963               NA           44.98      6.05\n49                  Djibouti 1963               NA           47.30      6.56\n50         Equatorial Guinea 1963               NA           38.73      5.55\n51                   Eritrea 1963               NA           40.04      6.81\n52                  Ethiopia 1963               NA           39.49      6.87\n53                     Gabon 1963               NA           40.07      4.62\n54             Guinea-Bissau 1963               NA           43.89      5.52\n55                Madagascar 1963               NA           43.70      7.30\n56                Mozambique 1963               NA           39.98      6.60\n57                   Namibia 1963               NA           48.90      6.20\n58                     Niger 1963               NA           37.24      7.15\n59              South Africa 1963               NA           50.14      6.05\n60                    Angola 1964               NA           38.18      7.43\n61                Cape Verde 1964               NA           50.77      6.99\n62                      Chad 1964               NA           42.58      6.32\n63                   Comoros 1964               NA           45.75      6.98\n64          Congo, Dem. Rep. 1964               NA           45.36      6.07\n65                  Djibouti 1964               NA           47.80      6.60\n66         Equatorial Guinea 1964               NA           39.08      5.57\n67                   Eritrea 1964               NA           40.41      6.78\n68                  Ethiopia 1964               NA           39.36      6.87\n69                     Gabon 1964               NA           40.70      4.69\n70             Guinea-Bissau 1964               NA           44.15      5.32\n71                Madagascar 1964               NA           44.28      7.30\n72                   Namibia 1964               NA           49.48      6.22\n73                     Niger 1964               NA           37.36      7.19\n74              South Africa 1964               NA           50.52      5.98\n75                    Angola 1965               NA           38.74      7.43\n76                Cape Verde 1965               NA           51.00      6.99\n77                      Chad 1965               NA           43.01      6.34\n78                   Comoros 1965               NA           46.18      7.00\n79          Congo, Dem. Rep. 1965               NA           45.77      6.09\n80                  Djibouti 1965               NA           48.33      6.63\n81         Equatorial Guinea 1965               NA           39.44      5.60\n82                   Eritrea 1965               NA           40.81      6.75\n83                  Ethiopia 1965               NA           38.13      6.86\n84                     Gabon 1965               NA           41.42      4.77\n85             Guinea-Bissau 1965               NA           44.39      5.14\n86                   Namibia 1965               NA           50.05      6.24\n87                     Niger 1965               NA           37.49      7.22\n88              South Africa 1965               NA           50.91      5.91\n89                    Angola 1966               NA           39.28      7.42\n90                Cape Verde 1966               NA           51.32      6.99\n91                      Chad 1966               NA           43.48      6.36\n92                   Comoros 1966               NA           46.63      7.03\n93          Congo, Dem. Rep. 1966               NA           46.20      6.11\n94                  Djibouti 1966               NA           48.90      6.67\n95         Equatorial Guinea 1966               NA           39.78      5.62\n96                   Eritrea 1966               NA           41.22      6.73\n97                     Gabon 1966               NA           42.21      4.83\n98             Guinea-Bissau 1966               NA           44.63      5.05\n99                   Namibia 1966               NA           50.61      6.26\n100                    Niger 1966               NA           37.61      7.26\n101             South Africa 1966               NA           51.30      5.84\n102                   Angola 1967               NA           39.84      7.40\n103               Cape Verde 1967               NA           51.75      6.98\n104                     Chad 1967               NA           43.98      6.39\n105                  Comoros 1967               NA           47.10      7.04\n106         Congo, Dem. Rep. 1967               NA           46.66      6.14\n107                 Djibouti 1967               NA           49.53      6.70\n108        Equatorial Guinea 1967               NA           40.13      5.64\n109                  Eritrea 1967               NA           41.66      6.71\n110                    Gabon 1967               NA           43.06      4.90\n111            Guinea-Bissau 1967               NA           44.86      5.09\n112             South Africa 1967               NA           51.68      5.77\n113                   Angola 1968               NA           40.39      7.38\n114               Cape Verde 1968               NA           52.32      6.97\n115                     Chad 1968               NA           44.54      6.43\n116                  Comoros 1968               NA           47.58      7.06\n117         Congo, Dem. Rep. 1968               NA           47.14      6.16\n118                 Djibouti 1968               NA           50.23      6.74\n119        Equatorial Guinea 1968               NA           40.48      5.66\n120                  Eritrea 1968               NA           42.10      6.69\n121                    Gabon 1968               NA           43.90      4.96\n122            Guinea-Bissau 1968               NA           45.09      5.30\n123             South Africa 1968               NA           52.04      5.70\n124                   Angola 1969               NA           40.95      7.34\n125                  Comoros 1969               NA           48.09      7.06\n126                 Djibouti 1969               NA           50.99      6.77\n127        Equatorial Guinea 1969               NA           40.82      5.67\n128                    Gabon 1969               NA           44.74      5.02\n129            Guinea-Bissau 1969               NA           45.29      5.64\n130             South Africa 1969               NA           52.41      5.64\n131                 Djibouti 1970               NA           51.75      6.80\n132        Equatorial Guinea 1970               NA           41.17      5.68\n133                    Gabon 1970               NA           45.55      5.08\n134            Guinea-Bissau 1970               NA           45.50      6.07\n135             South Africa 1970               NA           52.77      5.59\n136                   Angola 1971               NA           42.06      7.26\n137                 Djibouti 1971               NA           52.51      6.83\n138        Equatorial Guinea 1971               NA           41.52      5.68\n139                    Gabon 1971               NA           46.35      5.14\n140            Guinea-Bissau 1971               NA           45.71      6.49\n141             South Africa 1971               NA           53.11      5.54\n142                   Angola 1972               NA           42.62      7.23\n143                 Djibouti 1972               NA           53.20      6.84\n144        Equatorial Guinea 1972               NA           41.87      5.68\n145                    Gabon 1972               NA           47.13      5.21\n146            Guinea-Bissau 1972               NA           45.91      6.81\n147             South Africa 1972               NA           53.44      5.48\n148                   Angola 1973               NA           43.17      7.21\n149                 Djibouti 1973               NA           53.83      6.83\n150        Equatorial Guinea 1973               NA           42.21      5.68\n151                    Gabon 1973               NA           47.90      5.28\n152            Guinea-Bissau 1973               NA           46.12      6.98\n153             South Africa 1973               NA           53.77      5.42\n154                   Angola 1974               NA           43.71      7.19\n155                 Djibouti 1974               NA           54.38      6.82\n156        Equatorial Guinea 1974               NA           42.56      5.68\n157                    Gabon 1974               NA           48.68      5.34\n158            Guinea-Bissau 1974               NA           46.33      6.99\n159                   Angola 1975               NA           44.22      7.19\n160                 Djibouti 1975               NA           54.85      6.78\n161        Equatorial Guinea 1975               NA           42.91      5.67\n162                    Gabon 1975               NA           49.45      5.41\n163            Guinea-Bissau 1975               NA           46.54      6.87\n164                   Angola 1976               NA           44.68      7.19\n165        Equatorial Guinea 1976               NA           43.28      5.68\n166                    Gabon 1976               NA           50.23      5.48\n167                   Angola 1977               NA           45.12      7.19\n168        Equatorial Guinea 1977               NA           43.65      5.68\n169                    Gabon 1977               NA           51.01      5.54\n170                   Angola 1978               NA           45.50      7.19\n171        Equatorial Guinea 1978               NA           44.04      5.69\n172                   Angola 1979               NA           45.84      7.20\n173        Equatorial Guinea 1979               NA           44.44      5.71\n174        Equatorial Guinea 1980               NA           44.85      5.73\n175        Equatorial Guinea 1981               NA           45.26      5.75\n176                  Algeria 2016               NA           76.50        NA\n177                   Angola 2016               NA           60.00        NA\n178                    Benin 2016               NA           62.60        NA\n179                 Botswana 2016               NA           60.13        NA\n180             Burkina Faso 2016               NA           61.20        NA\n181                  Burundi 2016               NA           61.40        NA\n182                 Cameroon 2016               NA           59.70        NA\n183               Cape Verde 2016               NA           73.10        NA\n184 Central African Republic 2016               NA           51.04        NA\n185                     Chad 2016               NA           58.01        NA\n186                  Comoros 2016               NA           68.20        NA\n187         Congo, Dem. Rep. 2016               NA           61.51        NA\n188              Congo, Rep. 2016               NA           61.50        NA\n189            Cote d'Ivoire 2016               NA           59.71        NA\n190                 Djibouti 2016               NA           64.51        NA\n191                    Egypt 2016               NA           71.70        NA\n192        Equatorial Guinea 2016               NA           61.00        NA\n193                  Eritrea 2016               NA           60.80        NA\n194                 Ethiopia 2016               NA           65.70        NA\n195                    Gabon 2016               NA           66.81        NA\n196                   Gambia 2016               NA           68.20        NA\n197                    Ghana 2016               NA           65.80        NA\n198                   Guinea 2016               NA           59.60        NA\n199            Guinea-Bissau 2016               NA           55.90        NA\n200                    Kenya 2016               NA           65.20        NA\n201                  Lesotho 2016               NA           48.86        NA\n202                  Liberia 2016               NA           64.63        NA\n203                    Libya 2016               NA           73.21        NA\n204               Madagascar 2016               NA           63.70        NA\n205                   Malawi 2016               NA           60.90        NA\n206                     Mali 2016               NA           60.40        NA\n207               Mauritania 2016               NA           69.80        NA\n208                Mauritius 2016               NA           74.70        NA\n209                  Morocco 2016               NA           74.80        NA\n210               Mozambique 2016               NA           58.12        NA\n211                  Namibia 2016               NA           64.30        NA\n212                    Niger 2016               NA           61.30        NA\n213                  Nigeria 2016               NA           65.51        NA\n214                   Rwanda 2016               NA           66.10        NA\n215                  Senegal 2016               NA           65.60        NA\n216               Seychelles 2016               NA           74.20        NA\n217             Sierra Leone 2016               NA           59.07        NA\n218             South Africa 2016               NA           61.40        NA\n219                    Sudan 2016               NA           67.80        NA\n220                Swaziland 2016               NA           53.88        NA\n221                 Tanzania 2016               NA           64.91        NA\n222                     Togo 2016               NA           61.90        NA\n223                  Tunisia 2016               NA           77.60        NA\n224                   Uganda 2016               NA           61.91        NA\n225                   Zambia 2016               NA           57.10        NA\n226                 Zimbabwe 2016               NA           61.69        NA\n    population         gdp continent          region\n1       202316          NA    Africa  Western Africa\n2      3002596   750173439    Africa   Middle Africa\n3        83636          NA    Africa  Eastern Africa\n4       252115          NA    Africa   Middle Africa\n5      1407631          NA    Africa  Eastern Africa\n6       499189   887289809    Africa   Middle Africa\n7      3577413          NA    Africa  Western Africa\n8       616407          NA    Africa  Western Africa\n9      3395212  1020197091    Africa  Western Africa\n10    17396367 38336071006    Africa Southern Africa\n11     5367287          NA    Africa   Middle Africa\n12      205958          NA    Africa  Western Africa\n13     3061423   760658941    Africa   Middle Africa\n14      191828          NA    Africa  Eastern Africa\n15    15637715  4451156989    Africa   Middle Africa\n16       88499          NA    Africa  Eastern Africa\n17      255100          NA    Africa   Middle Africa\n18     1441297          NA    Africa  Eastern Africa\n19    22671131          NA    Africa  Eastern Africa\n20      504174  1018309175    Africa   Middle Africa\n21      623413          NA    Africa  Western Africa\n22     5223621  2130711083    Africa  Eastern Africa\n23     7643290          NA    Africa  Eastern Africa\n24      617282          NA    Africa Southern Africa\n25     3493636  1066579260    Africa  Western Africa\n26    46144154 12861030560    Africa  Western Africa\n27    17850045 39810250010    Africa Southern Africa\n28     5465905          NA    Africa   Middle Africa\n29      210866          NA    Africa  Western Africa\n30     3122357   801431143    Africa   Middle Africa\n31      194960          NA    Africa  Eastern Africa\n32    16041247  5394833319    Africa   Middle Africa\n33       94200          NA    Africa  Eastern Africa\n34      257940          NA    Africa   Middle Africa\n35     1476321          NA    Africa  Eastern Africa\n36    23221331          NA    Africa  Eastern Africa\n37      509806  1094165180    Africa   Middle Africa\n38      629973          NA    Africa  Western Africa\n39     5352674  2179101018    Africa  Eastern Africa\n40     7799396          NA    Africa  Eastern Africa\n41      632658          NA    Africa Southern Africa\n42     3596613  1176209886    Africa  Western Africa\n43    18322335 42269436973    Africa Southern Africa\n44     5565808          NA    Africa   Middle Africa\n45      216913          NA    Africa  Western Africa\n46     3184775   788612621    Africa   Middle Africa\n47      198205          NA    Africa  Eastern Africa\n48    16461914  5676119396    Africa   Middle Africa\n49      100622          NA    Africa  Eastern Africa\n50      260990          NA    Africa   Middle Africa\n51     1512671          NA    Africa  Eastern Africa\n52    23798378          NA    Africa  Eastern Africa\n53      516270  1160826485    Africa   Middle Africa\n54      636593          NA    Africa  Western Africa\n55     5486593  2158848417    Africa  Eastern Africa\n56     7961458          NA    Africa  Eastern Africa\n57      648668          NA    Africa Southern Africa\n58     3703159  1287105652    Africa  Western Africa\n59    18809939 45386200940    Africa Southern Africa\n60     5665701          NA    Africa   Middle Africa\n61      223854          NA    Africa  Western Africa\n62     3247798   768811034    Africa   Middle Africa\n63      201665          NA    Africa  Eastern Africa\n64    16903899  5537609393    Africa   Middle Africa\n65      107584          NA    Africa  Eastern Africa\n66      264743          NA    Africa   Middle Africa\n67     1550297          NA    Africa  Eastern Africa\n68    24396965          NA    Africa  Eastern Africa\n69      523793  1213695790    Africa   Middle Africa\n70      643962          NA    Africa  Western Africa\n71     5625401  2244393192    Africa  Eastern Africa\n72      665297          NA    Africa Southern Africa\n73     3811813  1288792274    Africa  Western Africa\n74    19308166 48989793258    Africa Southern Africa\n75     5765025          NA    Africa   Middle Africa\n76      231427          NA    Africa  Western Africa\n77     3310921   773471780    Africa   Middle Africa\n78      205412          NA    Africa  Eastern Africa\n79    17369859  5592838673    Africa   Middle Africa\n80      114963          NA    Africa  Eastern Africa\n81      269427          NA    Africa   Middle Africa\n82     1589187          NA    Africa  Eastern Africa\n83    25013551          NA    Africa  Eastern Africa\n84      532512  1314837134    Africa   Middle Africa\n85      652566          NA    Africa  Western Africa\n86      682553          NA    Africa Southern Africa\n87     3921581  1377973629    Africa  Western Africa\n88    19813947 53347940265    Africa Southern Africa\n89     5863568          NA    Africa   Middle Africa\n90      239765          NA    Africa  Western Africa\n91     3373563   759494431    Africa   Middle Africa\n92      209536          NA    Africa  Eastern Africa\n93    17861860  5971780635    Africa   Middle Africa\n94      122868          NA    Africa  Eastern Africa\n95      275470          NA    Africa   Middle Africa\n96     1629333          NA    Africa  Eastern Africa\n97      542562  1374110052    Africa   Middle Africa\n98      662597          NA    Africa  Western Africa\n99      700316          NA    Africa Southern Africa\n100    4032210  1372702919    Africa  Western Africa\n101   20325230 55715759234    Africa Southern Africa\n102    5962831          NA    Africa   Middle Africa\n103     248733          NA    Africa  Western Africa\n104    3436227   765321282    Africa   Middle Africa\n105     214038          NA    Africa  Eastern Africa\n106   18378189  5912914485    Africa   Middle Africa\n107     131403          NA    Africa  Eastern Africa\n108     282445          NA    Africa   Middle Africa\n109    1670821          NA    Africa  Eastern Africa\n110     553829  1430656781    Africa   Middle Africa\n111     673893          NA    Africa  Western Africa\n112   20843785 59725342237    Africa Southern Africa\n113    6066094          NA    Africa   Middle Africa\n114     257478          NA    Africa  Western Africa\n115    3500778   761822089    Africa   Middle Africa\n116     218794          NA    Africa  Eastern Africa\n117   18913177  6169103240    Africa   Middle Africa\n118     140461          NA    Africa  Eastern Africa\n119     288701          NA    Africa   Middle Africa\n120    1713846          NA    Africa  Eastern Africa\n121     565878  1466549111    Africa   Middle Africa\n122     686155          NA    Africa  Western Africa\n123   21374931 62205953376    Africa Southern Africa\n124    6177703          NA    Africa   Middle Africa\n125     223629          NA    Africa  Eastern Africa\n126     149891          NA    Africa  Eastern Africa\n127     292014          NA    Africa   Middle Africa\n128     578114  1585088962    Africa   Middle Africa\n129     698917          NA    Africa  Western Africa\n130   21926165 65139570532    Africa Southern Africa\n131     159667          NA    Africa  Eastern Africa\n132     290905          NA    Africa   Middle Africa\n133     590119  1722664256    Africa   Middle Africa\n134     711828   104038537    Africa  Western Africa\n135   22502502 68558449204    Africa Southern Africa\n136    6437645          NA    Africa   Middle Africa\n137     169370          NA    Africa  Eastern Africa\n138     284915          NA    Africa   Middle Africa\n139     601734  1899387747    Africa   Middle Africa\n140     724863    99969624    Africa  Western Africa\n141   23106806 71492066360    Africa Southern Africa\n142    6587647          NA    Africa   Middle Africa\n143     179212          NA    Africa  Eastern Africa\n144     274906          NA    Africa   Middle Africa\n145     613129  2114720779    Africa   Middle Africa\n146     738117   106342548    Africa  Western Africa\n147   23736489 72675108212    Africa Southern Africa\n148    6750215          NA    Africa   Middle Africa\n149     190536          NA    Africa  Eastern Africa\n150     262399          NA    Africa   Middle Africa\n151     624625  2330050819    Africa   Middle Africa\n152     751512   107522836    Africa  Western Africa\n153   24384538 75997832835    Africa Southern Africa\n154    6923749          NA    Africa   Middle Africa\n155     205157          NA    Africa  Eastern Africa\n156     249587          NA    Africa   Middle Africa\n157     636702  3250120203    Africa   Middle Africa\n158     764974   112425062    Africa  Western Africa\n159    7107334          NA    Africa   Middle Africa\n160     224182          NA    Africa  Eastern Africa\n161     238240          NA    Africa   Middle Africa\n162     649719  3873822005    Africa   Middle Africa\n163     778482   121245465    Africa  Western Africa\n164    7299508          NA    Africa   Middle Africa\n165     228491          NA    Africa   Middle Africa\n166     663774  5253884186    Africa   Middle Africa\n167    7501320          NA    Africa   Middle Africa\n168     220352          NA    Africa   Middle Africa\n169     678786  4592835688    Africa   Middle Africa\n170    7717139          NA    Africa   Middle Africa\n171     215284          NA    Africa   Middle Africa\n172    7952882          NA    Africa   Middle Africa\n173     215014          NA    Africa   Middle Africa\n174     220605          NA    Africa   Middle Africa\n175     232934          NA    Africa   Middle Africa\n176         NA          NA    Africa Northern Africa\n177         NA          NA    Africa   Middle Africa\n178         NA          NA    Africa  Western Africa\n179         NA          NA    Africa Southern Africa\n180         NA          NA    Africa  Western Africa\n181         NA          NA    Africa  Eastern Africa\n182         NA          NA    Africa   Middle Africa\n183         NA          NA    Africa  Western Africa\n184         NA          NA    Africa   Middle Africa\n185         NA          NA    Africa   Middle Africa\n186         NA          NA    Africa  Eastern Africa\n187         NA          NA    Africa   Middle Africa\n188         NA          NA    Africa   Middle Africa\n189         NA          NA    Africa  Western Africa\n190         NA          NA    Africa  Eastern Africa\n191         NA          NA    Africa Northern Africa\n192         NA          NA    Africa   Middle Africa\n193         NA          NA    Africa  Eastern Africa\n194         NA          NA    Africa  Eastern Africa\n195         NA          NA    Africa   Middle Africa\n196         NA          NA    Africa  Western Africa\n197         NA          NA    Africa  Western Africa\n198         NA          NA    Africa  Western Africa\n199         NA          NA    Africa  Western Africa\n200         NA          NA    Africa  Eastern Africa\n201         NA          NA    Africa Southern Africa\n202         NA          NA    Africa  Western Africa\n203         NA          NA    Africa Northern Africa\n204         NA          NA    Africa  Eastern Africa\n205         NA          NA    Africa  Eastern Africa\n206         NA          NA    Africa  Western Africa\n207         NA          NA    Africa  Western Africa\n208         NA          NA    Africa  Eastern Africa\n209         NA          NA    Africa Northern Africa\n210         NA          NA    Africa  Eastern Africa\n211         NA          NA    Africa Southern Africa\n212         NA          NA    Africa  Western Africa\n213         NA          NA    Africa  Western Africa\n214         NA          NA    Africa  Eastern Africa\n215         NA          NA    Africa  Western Africa\n216         NA          NA    Africa  Eastern Africa\n217         NA          NA    Africa  Western Africa\n218         NA          NA    Africa Southern Africa\n219         NA          NA    Africa Northern Africa\n220         NA          NA    Africa Southern Africa\n221         NA          NA    Africa  Eastern Africa\n222         NA          NA    Africa  Western Africa\n223         NA          NA    Africa Northern Africa\n224         NA          NA    Africa  Eastern Africa\n225         NA          NA    Africa  Eastern Africa\n226         NA          NA    Africa  Eastern Africa\n```\n:::\n:::\n\n\nIt looks like there is missing data for years 1960 to 1981 and 2016. To\nlook at a full dataset for one year, we will focus on year 2000.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#subset`africadata` to only \n#view year 2000\n\nfullyear <- africadata %>% filter(year == 2000)\nstr(fullyear)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t51 obs. of  9 variables:\n $ country         : Factor w/ 185 levels \"Albania\",\"Algeria\",..: 2 3 18 22 26 27 29 31 32 33 ...\n $ year            : int  2000 2000 2000 2000 2000 2000 2000 2000 2000 2000 ...\n $ infant_mortality: num  33.9 128.3 89.3 52.4 96.2 ...\n $ life_expectancy : num  73.3 52.3 57.2 47.6 52.6 46.7 54.3 68.4 45.3 51.5 ...\n $ fertility       : num  2.51 6.84 5.98 3.41 6.59 7.06 5.62 3.7 5.45 7.35 ...\n $ population      : num  31183658 15058638 6949366 1736579 11607944 ...\n $ gdp             : num  5.48e+10 9.13e+09 2.25e+09 5.63e+09 2.61e+09 ...\n $ continent       : Factor w/ 5 levels \"Africa\",\"Americas\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ region          : Factor w/ 22 levels \"Australia and New Zealand\",..: 11 10 20 17 20 5 10 20 10 10 ...\n```\n:::\n\n```{.r .cell-code}\nsummary(fullyear)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         country        year      infant_mortality life_expectancy\n Algeria     : 1   Min.   :2000   Min.   : 12.30   Min.   :37.60  \n Angola      : 1   1st Qu.:2000   1st Qu.: 60.80   1st Qu.:51.75  \n Benin       : 1   Median :2000   Median : 80.30   Median :54.30  \n Botswana    : 1   Mean   :2000   Mean   : 78.93   Mean   :56.36  \n Burkina Faso: 1   3rd Qu.:2000   3rd Qu.:103.30   3rd Qu.:60.00  \n Burundi     : 1   Max.   :2000   Max.   :143.30   Max.   :75.00  \n (Other)     :45                                                  \n   fertility       population             gdp               continent \n Min.   :1.990   Min.   :    81154   Min.   :2.019e+08   Africa  :51  \n 1st Qu.:4.150   1st Qu.:  2304687   1st Qu.:1.274e+09   Americas: 0  \n Median :5.550   Median :  8799165   Median :3.238e+09   Asia    : 0  \n Mean   :5.156   Mean   : 15659800   Mean   :1.155e+10   Europe  : 0  \n 3rd Qu.:5.960   3rd Qu.: 17391242   3rd Qu.:8.654e+09   Oceania : 0  \n Max.   :7.730   Max.   :122876723   Max.   :1.329e+11                \n                                                                      \n                       region  \n Eastern Africa           :16  \n Western Africa           :16  \n Middle Africa            : 8  \n Northern Africa          : 6  \n Southern Africa          : 5  \n Australia and New Zealand: 0  \n (Other)                  : 0  \n```\n:::\n:::\n\n\n`fullyear` contains only data for year 2000 for the African countries.\nThis is shown through the `summary` as the statistics all equal 2000 for\nthe year column. The new dataset had 51 observations with 9 columns.\n\n## Plotting with full dataset (Year 2000)\n\nWe will plot the same scatterplots as above with the `fullyear` dataset.\nThere should not be any missing data, and no warning should pop up from\nremoving data points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#plot life expectancy as \n#a function of infant mortality with no missing data\nggplot(fullyear) +\n  geom_point(aes(infant_mortality, life_expectancy))\n```\n\n::: {.cell-output-display}\n![Year 2000 life expectancy vs infant mortality](coding_exercise_files/figure-html/fig3-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#| label: fig4\n#| fig-cap: Year 2000 life expectancy vs population size\n#plot life expectancy as \n#a function of population size with no missing data\nggplot(fullyear) +\n  geom_point(aes(population, life_expectancy))+\n  scale_x_continuous(trans = \"log\")\n```\n\n::: {.cell-output-display}\n![Year 2000 life expectancy vs infant mortality](coding_exercise_files/figure-html/fig3-2.png){width=672}\n:::\n:::\n\n\nBased on these figures, we see a similar negative correlation between\nlife expectancy and infant mortality as in the previous graphs. However,\nthere does not appear to be a correlation between population size and\nlife expectancy when looking at year 2000. To use a more objective\nmeasure to observe the relationship between population size and life\nexpectancy, let's jump into statistical measures.\n\n## Linear modeling\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#fitting linear model for population size\n#predicting life expectancy\nfit1 <- lm(life_expectancy~infant_mortality, data = fullyear)\nfit2 <- lm(life_expectancy~population, data = fullyear)\n\n#printing results of the linear models\nsummary(fit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy ~ infant_mortality, data = fullyear)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-22.6651  -3.7087   0.9914   4.0408   8.6817 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      71.29331    2.42611  29.386  < 2e-16 ***\ninfant_mortality -0.18916    0.02869  -6.594 2.83e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.221 on 49 degrees of freedom\nMultiple R-squared:  0.4701,\tAdjusted R-squared:  0.4593 \nF-statistic: 43.48 on 1 and 49 DF,  p-value: 2.826e-08\n```\n:::\n\n```{.r .cell-code}\nsummary(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = life_expectancy ~ population, data = fullyear)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-18.429  -4.602  -2.568   3.800  18.802 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 5.593e+01  1.468e+00  38.097   <2e-16 ***\npopulation  2.756e-08  5.459e-08   0.505    0.616    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.524 on 49 degrees of freedom\nMultiple R-squared:  0.005176,\tAdjusted R-squared:  -0.01513 \nF-statistic: 0.2549 on 1 and 49 DF,  p-value: 0.6159\n```\n:::\n:::\n\nLooking at the summary results, infant mortality appears to be a valid predictor of life expectancy (p-value<0.001). Life expectancy decreases by 0.189 years with each increase in infant mortality (SE = 0.029, t = -6.594). \n\nPopulation size is not a valid predictor of life expectancy because the p-value is 0.616 which is not statistically significant.\n\n\n\n\n\n*Nathan Greenslit's Work Below*\n\n# Load Broom Library\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'broom' was built under R version 4.2.2\n```\n:::\n:::\n\n\n\n# Looking at whole dataset\n\n::: {.cell}\n\n```{.r .cell-code}\ngapminder<- gapminder\n```\n:::\n\n\n# Looking at only the United States\n\n::: {.cell}\n\n```{.r .cell-code}\nus <-\n  gapminder %>% \n  filter(country %in% \"United States\")\nstr(us)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t57 obs. of  9 variables:\n $ country         : Factor w/ 185 levels \"Albania\",\"Algeria\",..: 176 176 176 176 176 176 176 176 176 176 ...\n $ year            : int  1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 ...\n $ infant_mortality: num  25.9 25.4 24.9 24.4 23.8 23.3 22.7 22 21.3 20.6 ...\n $ life_expectancy : num  69.9 70.3 70.2 70 70.3 ...\n $ fertility       : num  3.67 3.63 3.48 3.35 3.22 2.93 2.71 2.56 2.47 2.46 ...\n $ population      : num  1.86e+08 1.89e+08 1.92e+08 1.95e+08 1.97e+08 ...\n $ gdp             : num  2.48e+12 2.54e+12 2.69e+12 2.81e+12 2.97e+12 ...\n $ continent       : Factor w/ 5 levels \"Africa\",\"Americas\",..: 2 2 2 2 2 2 2 2 2 2 ...\n $ region          : Factor w/ 22 levels \"Australia and New Zealand\",..: 12 12 12 12 12 12 12 12 12 12 ...\n```\n:::\n\n```{.r .cell-code}\nsummary(us) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                country        year      infant_mortality life_expectancy\n United States      :57   Min.   :1960   Min.   : 5.600   Min.   :69.91  \n Albania            : 0   1st Qu.:1974   1st Qu.: 6.975   1st Qu.:72.08  \n Algeria            : 0   Median :1988   Median :10.100   Median :75.02  \n Angola             : 0   Mean   :1988   Mean   :12.375   Mean   :74.81  \n Antigua and Barbuda: 0   3rd Qu.:2002   3rd Qu.:16.900   3rd Qu.:77.10  \n Argentina          : 0   Max.   :2016   Max.   :25.900   Max.   :79.10  \n (Other)            : 0                  NA's   :1                       \n   fertility       population             gdp               continent \n Min.   :1.740   Min.   :186176524   Min.   :2.479e+12   Africa  : 0  \n 1st Qu.:1.870   1st Qu.:216524624   1st Qu.:4.238e+12   Americas:57  \n Median :2.000   Median :246645306   Median :6.132e+12   Asia    : 0  \n Mean   :2.153   Mean   :250998907   Mean   :6.652e+12   Europe  : 0  \n 3rd Qu.:2.080   3rd Qu.:286464860   3rd Qu.:9.171e+12   Oceania : 0  \n Max.   :3.670   Max.   :321773631   Max.   :1.174e+13                \n NA's   :1       NA's   :1           NA's   :5                        \n                       region  \n Northern America         :57  \n Australia and New Zealand: 0  \n Caribbean                : 0  \n Central America          : 0  \n Central Asia             : 0  \n Eastern Africa           : 0  \n (Other)                  : 0  \n```\n:::\n:::\n\n*Looks like 2016 has NA*\n\n# Filter out NAs in 2016 in Fertility\n\n::: {.cell}\n\n```{.r .cell-code}\nus.clean <- \n  us %>%\n  filter(!is.na(fertility))\n```\n:::\n\n\n\n\n# Fertility in the US over time\n\n::: {.cell}\n\n```{.r .cell-code}\nus.clean %>% ggplot() +\n  geom_point(\n    aes(\n      x = year,\n      y = fertility),\n    color = \"darkgreen\") + \n  geom_line(\n    aes(\n      x = year,\n      y = fertility),\n    color = \"darkgreen\")+\n  labs(\n    x = \"Year\",\n    y = \"Fertility (Avg. # Children per Woman)\",\n    title = \"Fertility in the United States (1960-2015)\")+\n  theme_bw() +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](coding_exercise_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n*There is a significant drop in the number of children per woman over time. There could be due to a few things: (1) An increase in women's empowerment in the workforce, (2) increased cost of raising children, and (3) lower child mortality. With the data set we have, I am using infant_mortality to explore the 3rd hypothesis: a decrease in child mortality is correlated to a drop in children per woman.*\n\n# Infant Mortality in the US over time\n\n::: {.cell}\n\n```{.r .cell-code}\nus.clean %>% ggplot() +\n  geom_point(\n    aes(\n      x = year,\n      y = infant_mortality),\n    color = \"darkgreen\") + \n  geom_line(\n    aes(\n      x = year,\n      y = infant_mortality),\n    color = \"darkgreen\")+\n  labs(\n    x = \"Year\",\n    y = \"Infant Mortality (Infant Deaths per 1000)\",\n    title = \"Infant Mortality in the United States (1960-2015)\")+\n  theme_bw() +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](coding_exercise_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n# Fertility as a function of Infant Mortality\n\n::: {.cell}\n\n```{.r .cell-code}\nus.clean %>% ggplot() +\n  geom_point(\n    aes(\n      x = infant_mortality,\n      y = fertility),\n    color = \"darkblue\") + \n  #geom_line(\n  #  aes(\n  #    x = infant_mortality,\n  #    y = fertility),\n  #  color = \"darkblue\")+\ngeom_smooth(aes(\n  x = infant_mortality, \n  y = fertility),\n  method = lm) +\n  labs(\n    x = \"Infant Mortality (Infant Deaths per 1000)\",\n    y = \"Fertility (Avg. # Children per Woman)\",\n    title = \"Fertility as a function of Infant Mortality\")+\n  theme_bw() +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](coding_exercise_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n# Linear Model to examine correlation between Fertility Drop and Decrease in Infant Mortality\n\n::: {.cell}\n\n```{.r .cell-code}\nfert.fit <- lm(infant_mortality~fertility, data = us.clean)\nsummary(fert.fit)\n```\n:::\n\n\n\n# Making lm() output to a table using `broom` package\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(fert.fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    -8.85      2.66     -3.32 1.60e- 3\n2 fertility       9.86      1.21      8.16 5.39e-11\n```\n:::\n:::\n\n*A p-value of 5.38E-11 may indicate that there is a significant correlation between the drop in fertility and decrease in infant mortality in the US. An R2 value of .54 indicates that infant mortality is an okay predictor of fertility, but there is most likely other variables that play a role.*\n\n\n\n\n",
    "supporting": [
      "coding_exercise_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}