{
  "hash": "6d998c9d940fd705161aa397de10b22f",
  "result": {
    "markdown": "---\ntitle: \"Tidy Tuesday Exercise\"\noutput: \n  html_document:\n    toc: FALSE\n---\n\n\n***For this exercise, I will be using data cleaning and exploratory analysis on this week's TidyTuesday data set. The data is on [Hollywood Age Gaps](https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-02-14) showing the age difference between love interests on various films. The data set includes variables for Movie Title, Release Year, Director, and various character-related information.***\n\n## Possible questions to explore\n1. Does the average age difference change over different release years?\n2. Does age difference differ between mixed-gender and same-gender couples?\n3. What directors have the highest average age difference?\n\n\nTo begin, let's load the packages and the data set. \n\n## Load packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidytuesdayR)\nlibrary(tidyverse)\nlibrary(dplyr)\nlibrary(naniar)\nlibrary(forcats)\n```\n:::\n\n\n## Load data from TidyTuesday\nThis part of the code used taken from the `readme` file on the GitHub repository. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ntuesdata <- tidytuesdayR::tt_load('2023-02-14')\ntuesdata <- tidytuesdayR::tt_load(2023, week = 7)\n# load data and assign to age_gaps\nage_gaps <- tuesdata$age_gaps\n```\n:::\n\n\n## Overview of data\nFirst, let's see an overview of the data. \n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(age_gaps)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1,155\nColumns: 13\n$ movie_name         <chr> \"Harold and Maude\", \"Venus\", \"The Quiet American\", …\n$ release_year       <dbl> 1971, 2006, 2002, 1998, 2010, 1992, 2009, 1999, 199…\n$ director           <chr> \"Hal Ashby\", \"Roger Michell\", \"Phillip Noyce\", \"Joe…\n$ age_difference     <dbl> 52, 50, 49, 45, 43, 42, 40, 39, 38, 38, 36, 36, 35,…\n$ couple_number      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ actor_1_name       <chr> \"Ruth Gordon\", \"Peter O'Toole\", \"Michael Caine\", \"D…\n$ actor_2_name       <chr> \"Bud Cort\", \"Jodie Whittaker\", \"Do Thi Hai Yen\", \"T…\n$ character_1_gender <chr> \"woman\", \"man\", \"man\", \"man\", \"man\", \"man\", \"man\", …\n$ character_2_gender <chr> \"man\", \"woman\", \"woman\", \"woman\", \"man\", \"woman\", \"…\n$ actor_1_birthdate  <date> 1896-10-30, 1932-08-02, 1933-03-14, 1930-09-17, 19…\n$ actor_2_birthdate  <date> 1948-03-29, 1982-06-03, 1982-10-01, 1975-11-08, 19…\n$ actor_1_age        <dbl> 75, 74, 69, 68, 81, 59, 62, 69, 57, 77, 59, 56, 65,…\n$ actor_2_age        <dbl> 23, 24, 20, 23, 38, 17, 22, 30, 19, 39, 23, 20, 30,…\n```\n:::\n\n```{.r .cell-code}\nsummary(age_gaps)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  movie_name         release_year    director         age_difference \n Length:1155        Min.   :1935   Length:1155        Min.   : 0.00  \n Class :character   1st Qu.:1997   Class :character   1st Qu.: 4.00  \n Mode  :character   Median :2004   Mode  :character   Median : 8.00  \n                    Mean   :2001                      Mean   :10.42  \n                    3rd Qu.:2012                      3rd Qu.:15.00  \n                    Max.   :2022                      Max.   :52.00  \n couple_number   actor_1_name       actor_2_name       character_1_gender\n Min.   :1.000   Length:1155        Length:1155        Length:1155       \n 1st Qu.:1.000   Class :character   Class :character   Class :character  \n Median :1.000   Mode  :character   Mode  :character   Mode  :character  \n Mean   :1.398                                                           \n 3rd Qu.:2.000                                                           \n Max.   :7.000                                                           \n character_2_gender actor_1_birthdate    actor_2_birthdate     actor_1_age   \n Length:1155        Min.   :1889-04-16   Min.   :1906-10-06   Min.   :18.00  \n Class :character   1st Qu.:1953-05-16   1st Qu.:1965-03-25   1st Qu.:33.00  \n Mode  :character   Median :1964-10-03   Median :1974-07-30   Median :39.00  \n                    Mean   :1960-09-07   Mean   :1971-01-29   Mean   :40.64  \n                    3rd Qu.:1973-08-07   3rd Qu.:1982-04-07   3rd Qu.:47.00  \n                    Max.   :1996-06-01   Max.   :1996-11-11   Max.   :81.00  \n  actor_2_age   \n Min.   :17.00  \n 1st Qu.:25.00  \n Median :29.00  \n Mean   :30.21  \n 3rd Qu.:34.00  \n Max.   :68.00  \n```\n:::\n:::\n\nThere are 1155 observations with 13 variables. The earliest movie is from 1935 and the most recent from 2022. The maximum age difference is 52 years, and the other variables can use age and birthday of the actors to calculate age difference. Next, we can check for missing data points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#check for missing points\ngg_miss_var(age_gaps)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: The `guide` argument in `scale_*()` cannot be `FALSE`. This was deprecated in\nggplot2 3.3.4.\nℹ Please use \"none\" instead.\nℹ The deprecated feature was likely used in the naniar package.\n  Please report the issue at <https://github.com/njtierney/naniar/issues>.\n```\n:::\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#check for NAs\nany(is_na(age_gaps))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\nIt looks like this is a complete dataset! Next we can explore the data by each variable. \n\n## Exploring the data\nSince `age_difference` is our outcome of interest, we can look at the distribution of age differences. \n\n::: {.cell}\n\n```{.r .cell-code}\n#histogram of age differences\nhist(age_gaps$age_difference,\n     labels = TRUE,\n     xlab = \"Difference in age by year\",\n     main = \"Histogram of Age Differences\",\n     ylim = c(0,450),\n     xlim = c(0,60))\n```\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\nA majority of the age differences are below 20 years with most being below 5 years. The highest age difference is approximately 55 years.\n\nWe can also look at the distribution of observations based on release year. \n\n::: {.cell}\n\n```{.r .cell-code}\n#table function for count of observations for each year\ntable(age_gaps$release_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n1935 1936 1937 1939 1940 1942 1944 1946 1947 1948 1950 1951 1952 1953 1954 1955 \n   2    1    3    1    3    2    1    1    1    4    1    3    4    3    7    2 \n1956 1957 1958 1959 1960 1961 1962 1963 1964 1965 1966 1967 1968 1969 1970 1971 \n   3    4    5    2    2    4    3    5    4    5    1    7    1    3    2    3 \n1972 1973 1974 1975 1976 1977 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 \n   3    5    6    1    1    4    5    1    5    6    6    1    5    5    7    5 \n1989 1990 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 \n   9    6    7   13   15   14   36   18   35   28   50   34   38   50   38   38 \n2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 \n  34   40   46   47   44   28   34   34   30   33   40   44   35   40   20    5 \n2021 2022 \n   8    5 \n```\n:::\n:::\n\nMost of the data points are from ~1980 to 2019. \n\n### Question 1\nNext, we can look age difference based on release year. \n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(age_gaps, aes(release_year, age_difference))+\n  geom_point()+\n  labs(x = \"Release Year\",\n       y = \"Age Difference\",\n       title = \"Age difference by release year\")\n```\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\nNo clear relationship between release year and age difference but that could be due to a majority of the data points being from the last 50 years. We can also look at the average age difference per year. We can also look at the gender of the older character since character 1 is listed as the older character in the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(age_gaps, aes(release_year, age_difference, color = character_1_gender))+\n  geom_point()+\n  labs(x = \"Release Year\",\n       y = \"Age Difference\",\n       title = \"Age difference by release year\",\n       subtitle = \"based on older character gender\")+\n  theme_minimal()+\n  scale_color_brewer(palette = \"Paired\")\n```\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\nWhen the gender of the older character is added, there appears to be more older male characters compared to older female characters, and when females are older, the age difference tends to be below 15 years. There is an easily identifiable outlier around 1973 that has an age difference over 50. \n\nWe can also look at the mean age difference by release year. \n\n::: {.cell}\n\n```{.r .cell-code}\nage_gaps %>% \n  group_by(release_year) %>% \n  summarise(mean_age_diff = mean(age_difference)) %>% #average age difference for each release year\n  ggplot(aes(release_year, mean_age_diff))+\n  geom_line(color = \"darkslateblue\")+\n  labs(title = \"Average age difference by release year\",\n       x = \"Release Year\",\n       y = \"Average Age Difference\")\n```\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nThere still doesn't seem to be a clear relationship between release year and age difference, but there does seem to be a stabilization at approximately 10 years by 2000. \n\n### Question 2\nI would also like to explore if there is a a difference between mixed-gender and same-gender couples. First, I'll need to create a new variable called `relationship` to denote the groups.\n\n::: {.cell}\n\n```{.r .cell-code}\n#create relationship variable and reassign to age_gaps\nage_gaps <- age_gaps %>% \n  mutate(relationship = case_when(character_1_gender == \"man\" & character_2_gender == \"woman\" ~ \"man_woman\",\n                                  character_1_gender == \"woman\" & character_2_gender == \"man\" ~ \"man_woman\", #needed to account for either gender as character 1\n                                  character_1_gender == \"man\" & character_2_gender == \"man\" ~ \"man_man\",\n                                  character_1_gender == \"woman\" & character_2_gender == \"woman\" ~ \"woman_woman\"))\n\nglimpse(age_gaps)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1,155\nColumns: 14\n$ movie_name         <chr> \"Harold and Maude\", \"Venus\", \"The Quiet American\", …\n$ release_year       <dbl> 1971, 2006, 2002, 1998, 2010, 1992, 2009, 1999, 199…\n$ director           <chr> \"Hal Ashby\", \"Roger Michell\", \"Phillip Noyce\", \"Joe…\n$ age_difference     <dbl> 52, 50, 49, 45, 43, 42, 40, 39, 38, 38, 36, 36, 35,…\n$ couple_number      <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ actor_1_name       <chr> \"Ruth Gordon\", \"Peter O'Toole\", \"Michael Caine\", \"D…\n$ actor_2_name       <chr> \"Bud Cort\", \"Jodie Whittaker\", \"Do Thi Hai Yen\", \"T…\n$ character_1_gender <chr> \"woman\", \"man\", \"man\", \"man\", \"man\", \"man\", \"man\", …\n$ character_2_gender <chr> \"man\", \"woman\", \"woman\", \"woman\", \"man\", \"woman\", \"…\n$ actor_1_birthdate  <date> 1896-10-30, 1932-08-02, 1933-03-14, 1930-09-17, 19…\n$ actor_2_birthdate  <date> 1948-03-29, 1982-06-03, 1982-10-01, 1975-11-08, 19…\n$ actor_1_age        <dbl> 75, 74, 69, 68, 81, 59, 62, 69, 57, 77, 59, 56, 65,…\n$ actor_2_age        <dbl> 23, 24, 20, 23, 38, 17, 22, 30, 19, 39, 23, 20, 30,…\n$ relationship       <chr> \"man_woman\", \"man_woman\", \"man_woman\", \"man_woman\",…\n```\n:::\n:::\n\nNow we can group by relationship and plot age difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_gaps %>% \n  ggplot()+\n  geom_boxplot(aes(relationship, age_difference))+\n  labs(x = \"Relationship Type\",\n       y = \"Age Difference\",\n       title = \"Age difference by relationship type\")\n```\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\nIt looks like the man_woman and woman_woman tend to have a similar median age difference with man_man having a higher median age difference. The man_woman category also appears to be responsible for most of the high age differences as shown with the outliers. \n\n### Question 3\n\nFinally, let's look into the third exploratory question about directors and age differences.\n\n::: {.cell}\n\n```{.r .cell-code}\n#count the number of directors in the dataset\nlength(unique(age_gaps$director))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 510\n```\n:::\n:::\n\nThere are 510 directors in the dataset. Let's graph age difference by director.\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(age_gaps, aes(x = director, y = age_difference))+\n  geom_boxplot()+\n  labs()+\n  coord_flip()\n```\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nAlright, so we obviously have too many data points to really see any trends. Let's arrange the data be descending age difference and only look at the top 20 directors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_gaps2 <- age_gaps %>% \n  group_by(director) %>% #group by director\n  summarise(mean_age_diff = mean(age_difference)) %>% #create average age difference for each director\n  arrange(desc(mean_age_diff)) %>% #order by descending age difference\n  slice(1:20) #use only the top 20 rows\n\nggplot(age_gaps2, aes(x = fct_reorder(director, mean_age_diff), y = mean_age_diff))+ #needed to use fct_reorder to display ascending age difference rather than alphabetical \n  geom_point(color = \"blue\")+\n  labs(y = \"Average Age Difference\", \n       x = \"Director\",\n       title = \"Directors with highest average age difference\")+\n  coord_flip()+ #flipped axes so director names were easier to read\n  scale_y_reverse() #flipped axis to display in descending order\n```\n\n::: {.cell-output-display}\n![](tidytuesday_exercise_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\nHal Ashby have the highest average age difference between characters by far, followed by Katt Shea, Jon Amiel, and Irving Pichel which all had age differences over 35 years. \n\n",
    "supporting": [
      "tidytuesday_exercise_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}